-- 코드를 입력하세요
SELECT A.MEMBER_NAME
     , B.REVIEW_TEXT
     , TO_CHAR(B.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE A
    , REST_REVIEW B
    , (SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID ) C
WHERE A.MEMBER_ID = B.MEMBER_ID
    AND A.MEMBER_ID = C.MEMBER_ID
    AND C.REVIEW_CNT = (SELECT MAX(COUNT(REVIEW_ID))
                                FROM REST_REVIEW
                                GROUP BY MEMBER_ID)
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT;
                                
                               