-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH
     , CAR_ID
     , COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN ( SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                WHERE TO_CHAR(START_DATE,'YYYYMMDD') BETWEEN '20220801' AND '20221031'
                GROUP BY CAR_ID
                HAVING COUNT(CAR_ID) >= 5    
               )
    AND TO_CHAR(START_DATE,'YYYYMMDD') BETWEEN '20220801' AND '20221031'
GROUP BY TO_NUMBER(TO_CHAR(START_DATE, 'MM')), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;

